
/*

------ UTILS CLASS ------

// Copyright (c) 2013 Fabio Franchino. All rights reserved.
// MIT License
*/
function Utils(){}


Utils.convertMidiNoteToFrequency = function(note){
	return (440. * Math.pow( 2.0, (note-69.0)/12.0 ));
}


Utils.random = function(min,max){
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

Utils.rnd = function(min,max){
    return function(){
    	Math.floor(Math.random() * (max - min + 1)) + min;
    }
}


//+ Jonas Raoni Soares Silva
//@ http://jsfromhell.com/array/shuffle [v1.0]
Utils.shuffle = function(o){ //v1.0
    for(var j, x, i = o.length; i; j = Math.floor(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
    return o;
};


Utils.pickRandomFromStringSet = function(str, oct){
	var arr = (str instanceof Array) ? str : str.trim().split(' ');
	var octave = (oct) ? oct : 0;
	console.log(arr);
	return Utils.getMidiNoteFromNotation( arr[ Utils.random(0, arr.length-1) ] + octave );
}


Utils.getRandomChord = function(){
	var index = parseInt( Math.random() * Utils.chordsArray.length );
	return Utils.chordsArray[index]
}

Utils.getRandomScale = function(){
	var index = parseInt( Math.random() * Utils.scalesArray.length );
	return Utils.scalesArray[index]
}

Utils.getMidiNoteFromNotation = function(note){
	return Utils.notationKeys[note];
}


// source http://www.scripthica.com/
Utils.notationKeys = new Object();

	Utils.notationKeys["C-1"] = 0; 	Utils.notationKeys["C0"] = 12;	Utils.notationKeys["C1"] = 24;
	Utils.notationKeys["C#-1"] = 1;	Utils.notationKeys["C#0"] = 13;	Utils.notationKeys["C#1"] = 25;
	Utils.notationKeys["Db-1"] = 1;	Utils.notationKeys["Db0"] = 13;	Utils.notationKeys["Db1"] = 25;
	Utils.notationKeys["D-1"] = 2;	Utils.notationKeys["D0"] = 14;	Utils.notationKeys["D1"] = 26;
	Utils.notationKeys["D#-1"] = 3;	Utils.notationKeys["D#0"] = 15;	Utils.notationKeys["D#1"] = 27;
	Utils.notationKeys["Eb-1"] = 3;	Utils.notationKeys["Eb0"] = 15;	Utils.notationKeys["Eb1"] = 27;
	Utils.notationKeys["E-1"] = 4;	Utils.notationKeys["E0"] = 16;	Utils.notationKeys["E1"] = 28;
	Utils.notationKeys["F-1"] = 5;	Utils.notationKeys["F0"] = 17;	Utils.notationKeys["F1"] = 29;
	Utils.notationKeys["F#-1"] = 6;	Utils.notationKeys["F#0"] = 18;	Utils.notationKeys["F#1"] = 30;
	Utils.notationKeys["Gb-1"] = 6;	Utils.notationKeys["Gb0"] = 18;	Utils.notationKeys["Gb1"] = 30;
	Utils.notationKeys["G-1"] = 7;	Utils.notationKeys["G0"] = 19;	Utils.notationKeys["G1"] = 31;
	Utils.notationKeys["G#-1"] = 8;	Utils.notationKeys["G#0"] = 20;	Utils.notationKeys["G#1"] = 32;
	Utils.notationKeys["Ab-1"] = 8;	Utils.notationKeys["Ab0"] = 20;	Utils.notationKeys["Ab1"] = 32;
	Utils.notationKeys["A-1"] = 9;	Utils.notationKeys["A0"] = 21;	Utils.notationKeys["A1"] = 33;
	Utils.notationKeys["A#-1"] = 10;	Utils.notationKeys["A#0"] = 22;	Utils.notationKeys["A#1"] = 34;
	Utils.notationKeys["Bb-1"] = 10;	Utils.notationKeys["Bb0"] = 22;	Utils.notationKeys["Bb1"] = 34;
	Utils.notationKeys["B-1"] = 11;	Utils.notationKeys["B0"] = 23;	Utils.notationKeys["B1"] = 35;
	
	Utils.notationKeys["C2"] = 36; 	Utils.notationKeys["C3"] = 48;	Utils.notationKeys["C4"] = 60;
	Utils.notationKeys["C#2"] = 37;	Utils.notationKeys["C#3"] = 49;	Utils.notationKeys["C#4"] = 61;
	Utils.notationKeys["Db2"] = 37;	Utils.notationKeys["Db3"] = 49;	Utils.notationKeys["Db4"] = 61;
	Utils.notationKeys["D2"] = 38;	Utils.notationKeys["D3"] = 50;	Utils.notationKeys["D4"] = 62;
	Utils.notationKeys["D#2"] = 39;	Utils.notationKeys["D#3"] = 51;	Utils.notationKeys["D#4"] = 63;
	Utils.notationKeys["Eb2"] = 39;	Utils.notationKeys["Eb3"] = 51;	Utils.notationKeys["Eb4"] = 63;
	Utils.notationKeys["E2"] = 40;	Utils.notationKeys["E3"] = 52;	Utils.notationKeys["E4"] = 64;
	Utils.notationKeys["F2"] = 41;	Utils.notationKeys["F3"] = 53;	Utils.notationKeys["F4"] = 65;
	Utils.notationKeys["F#2"] = 42;	Utils.notationKeys["F#3"] = 54;	Utils.notationKeys["F#4"] = 66;
	Utils.notationKeys["Gb2"] = 42;	Utils.notationKeys["Gb3"] = 54;	Utils.notationKeys["Gb4"] = 66;
	Utils.notationKeys["G2"] = 43;	Utils.notationKeys["G3"] = 55;	Utils.notationKeys["G4"] = 67;
	Utils.notationKeys["G#2"] = 44;	Utils.notationKeys["G#3"] = 56;	Utils.notationKeys["G#4"] = 68;
	Utils.notationKeys["Ab2"] = 44;	Utils.notationKeys["Ab3"] = 56;	Utils.notationKeys["Ab4"] = 68;
	Utils.notationKeys["A2"] = 45;	Utils.notationKeys["A3"] = 57;	Utils.notationKeys["A4"] = 69;
	Utils.notationKeys["A#2"] = 46;	Utils.notationKeys["A#3"] = 58;	Utils.notationKeys["A#4"] = 70;
	Utils.notationKeys["Bb2"] = 46;	Utils.notationKeys["Bb3"] = 58;	Utils.notationKeys["Bb4"] = 70;
	Utils.notationKeys["B2"] = 47;	Utils.notationKeys["B3"] = 59;	Utils.notationKeys["B4"] = 71;

	Utils.notationKeys["C5"] = 72; 	Utils.notationKeys["C6"] = 84;	Utils.notationKeys["C7"] = 96;
	Utils.notationKeys["C#5"] = 73;	Utils.notationKeys["C#6"] = 85;	Utils.notationKeys["C#7"] = 97;
	Utils.notationKeys["Db5"] = 73;	Utils.notationKeys["Db6"] = 85;	Utils.notationKeys["Db7"] = 97;
	Utils.notationKeys["D5"] = 74;	Utils.notationKeys["D6"] = 86;	Utils.notationKeys["D7"] = 98;
	Utils.notationKeys["D#5"] = 75;	Utils.notationKeys["D#6"] = 87;	Utils.notationKeys["D#7"] = 99;
	Utils.notationKeys["Eb5"] = 75;	Utils.notationKeys["Eb6"] = 87;	Utils.notationKeys["Eb7"] = 99;
	Utils.notationKeys["E5"] = 76;	Utils.notationKeys["E6"] = 88;	Utils.notationKeys["E7"] = 100;
	Utils.notationKeys["F5"] = 77;	Utils.notationKeys["F6"] = 89;	Utils.notationKeys["F7"] = 101;
	Utils.notationKeys["F#5"] = 78;	Utils.notationKeys["F#6"] = 90;	Utils.notationKeys["F#7"] = 102;
	Utils.notationKeys["Gb5"] = 78;	Utils.notationKeys["Gb6"] = 90;	Utils.notationKeys["Gb7"] = 102;
	Utils.notationKeys["G5"] = 79;	Utils.notationKeys["G6"] = 91;	Utils.notationKeys["G7"] = 103;
	Utils.notationKeys["G#5"] = 80;	Utils.notationKeys["G#6"] = 92;	Utils.notationKeys["G#7"] = 104;
	Utils.notationKeys["Ab5"] = 80;	Utils.notationKeys["Ab6"] = 92;	Utils.notationKeys["Ab7"] = 104;
	Utils.notationKeys["A5"] = 81;	Utils.notationKeys["A6"] = 93;	Utils.notationKeys["A7"] = 105;
	Utils.notationKeys["A#5"] = 82;	Utils.notationKeys["A#6"] = 94;	Utils.notationKeys["A#7"] = 106;
	Utils.notationKeys["Bb5"] = 82;	Utils.notationKeys["Bb6"] = 94;	Utils.notationKeys["Bb7"] = 106;
	Utils.notationKeys["B5"] = 83;	Utils.notationKeys["B6"] = 95;	Utils.notationKeys["B7"] = 107;

	Utils.notationKeys["C8"] = 108; 	Utils.notationKeys["C9"] = 120;	
	Utils.notationKeys["C#8"] = 109;	Utils.notationKeys["C#9"] = 121;	
	Utils.notationKeys["Db8"] = 109;	Utils.notationKeys["Db9"] = 121;	
	Utils.notationKeys["D8"] = 110;	Utils.notationKeys["D9"] = 122;
	Utils.notationKeys["D#8"] = 111;	Utils.notationKeys["D#9"] = 123;	
	Utils.notationKeys["Eb8"] = 111;	Utils.notationKeys["Eb9"] = 123;	
	Utils.notationKeys["E8"] = 112;	Utils.notationKeys["E9"] = 124;	
	Utils.notationKeys["F8"] = 113;	Utils.notationKeys["F9"] = 125;	
	Utils.notationKeys["F#8"] = 114;	Utils.notationKeys["F#9"] = 126;
	Utils.notationKeys["Gb8"] = 114;	Utils.notationKeys["Gb9"] = 126;	
	Utils.notationKeys["G8"] = 115;	Utils.notationKeys["G9"] = 127;	
	Utils.notationKeys["G#8"] = 116;	
	Utils.notationKeys["Ab8"] = 116;	
	Utils.notationKeys["A8"] = 117;	
	Utils.notationKeys["A#8"] = 118;	
	Utils.notationKeys["Bb8"] = 118;	
	Utils.notationKeys["B8"] = 119;



Utils.chords = {
"Cmaj":"C E G ",
"C#maj":"C# F G# ",
"Dmaj":"D F# A ",
"D#maj":"D# G A# ",
"Emaj":"E G# B ",
"Fmaj":"F A C ",
"F#maj":"F# A# C# ",
"Gmaj":"G B D ",
"G#maj":"G# C D# ",
"Amaj":"A C# E ",
"A#maj":"A# D F ",
"Bmaj":"B D# F# ",
"Cm":"C D# G ",
"C#m":"C# E G# ",
"Dm":"D F A ",
"D#m":"D# F# A# ",
"Em":"E G B ",
"Fm":"F G# C ",
"F#m":"F# A C# ",
"Gm":"G A# D ",
"G#m":"G# B D# ",
"Am":"A C E ",
"A#m":"A# C# F ",
"Bm":"B D F# ",
"C7":"C E G A# ",
"C#7":"C# F G# B ",
"D7":"D F# A C ",
"D#7":"D# G A# C# ",
"E7":"E G# B D ",
"F7":"F A C D# ",
"F#7":"F# A# C# E ",
"G7":"G B D F ",
"G#7":"G# C D# F# ",
"A7":"A C# E G ",
"A#7":"A# D F G# ",
"B7":"B D# F# A ",
"Cmin7":"C D# G A# ",
"C#min7":"C# E G# B ",
"Dmin7":"D F A C ",
"D#min7":"D# F# A# C# ",
"Emin7":"E G B D ",
"Fmin7":"F G# C D# ",
"F#min7":"F# A C# E ",
"Gmin7":"G A# D F ",
"G#min7":"G# B D# F# ",
"Amin7":"A C E G ",
"A#min7":"A# C# F G# ",
"Bmin7":"B D F# A ",
"Cmaj7":"C E G B ",
"C#maj7":"C# F G# C ",
"Dmaj7":"D F# A C# ",
"D#maj7":"D# G A# D ",
"Emaj7":"E G# B D# ",
"Fmaj7":"F A C E ",
"F#maj7":"F# A# C# F ",
"Gmaj7":"G B D F# ",
"G#maj7":"G# C D# G ",
"Amaj7":"A C# E G# ",
"A#maj7":"A# D F A ",
"Bmaj7":"B D# F# A# ",
"Csus4":"C F G ",
"C#sus4":"C# F# G# ",
"Dsus4":"D G A ",
"D#sus4":"D# G# A# ",
"Esus4":"E A B ",
"Fsus4":"F A# C ",
"F#sus4":"F# B C# ",
"Gsus4":"G C D ",
"G#sus4":"G# C# D# ",
"Asus4":"A D E ",
"A#sus4":"A# D# F ",
"Bsus4":"B E F# ",
"C7sus4":"C F G A# ",
"C#7sus4":"C# F# G# B ",
"D7sus4":"D G A C ",
"D#7sus4":"D# G# A# C# ",
"E7sus4":"E A B D ",
"F7sus4":"F A# C D# ",
"F#7sus4":"F# B C# E ",
"G7sus4":"G C D F ",
"G#7sus4":"G# C# D# F# ",
"A7sus4":"A D E G ",
"A#7sus4":"A# D# F G# ",
"B7sus4":"B E F# A ",
"C6":"C E G A ",
"C#6":"C# F G# A# ",
"D6":"D F# A B ",
"D#6":"D# G A# C ",
"E6":"E G# B C# ",
"F6":"F A C D ",
"F#6":"F# A# C# D# ",
"G6":"G B D E ",
"G#6":"G# C D# F ",
"A6":"A C# E F# ",
"A#6":"A# D F G ",
"B6":"B D# F# G# ",
"Cmin6":"C D# G A ",
"C#min6":"C# E G# A# ",
"Dmin6":"D F A B ",
"D#min6":"D# F# A# C ",
"Emin6":"E G B C# ",
"Fmin6":"F G# C D ",
"F#min6":"F# A C# D# ",
"Gmin6":"G A# D E ",
"G#min6":"G# B D# F ",
"Amin6":"A C E F# ",
"A#min6":"A# C# F G ",
"Bmin6":"B D F# G# ",
"Cdim":"C D# F# ",
"C#dim":"C# E G ",
"Ddim":"D F G# ",
"D#dim":"D# F# A ",
"Edim":"E G A# ",
"Fdim":"F G# B ",
"F#dim":"F# A C ",
"Gdim":"G A# C# ",
"G#dim":"G# B D ",
"Adim":"A C D# ",
"A#dim":"A# C# E ",
"Bdim":"B D F ",
"Caug":"C E G# ",
"C#aug":"C# F A ",
"Daug":"D F# A# ",
"D#aug":"D# G B ",
"Eaug":"E G# C ",
"Faug":"F A C# ",
"F#aug":"F# A# D ",
"Gaug":"G B D# ",
"G#aug":"G# C E ",
"Aaug":"A C# F ",
"A#aug":"A# D F# ",
"Baug":"B D# G ",
"C7-5":"C E F# A# ",
"C#7-5":"C# F G B ",
"D7-5":"D F# G# C ",
"D#7-5":"D# G A C# ",
"E7-5":"E G# A# D ",
"F7-5":"F A B D# ",
"F#7-5":"F# A# C E ",
"G7-5":"G B C# F ",
"G#7-5":"G# C D F# ",
"A7-5":"A C# D# G ",
"A#7-5":"A# D E G# ",
"B7-5":"B D# F A ",
"C7+5":"C E G# A# ",
"C#7+5":"C# F A B ",
"D7+5":"D F# A# C ",
"D#7+5":"D# G B C# ",
"E7+5":"E G# C D ",
"F7+5":"F A C# D# ",
"F#7+5":"F# A# D E ",
"G7+5":"G B D# F ",
"G#7+5":"G# C E F# ",
"A7+5":"A C# F G ",
"A#7+5":"A# D F# G# ",
"B7+5":"B D# G A ",
"Cm7-5":"C D# F# A# ",
"C#m7-5":"C# E G B ",
"Dm7-5":"D F G# C ",
"D#m7-5":"D# F# A C# ",
"Em7-5":"E G A# D ",
"Fm7-5":"F G# B D# ",
"F#m7-5":"F# A C E ",
"Gm7-5":"G A# C# F ",
"G#m7-5":"G# B D F# ",
"Am7-5":"A C D# G ",
"A#m7-5":"A# C# E G# ",
"Bm7-5":"B D F A ",
"Cm/maj7":"C D# G B ",
"C#m/maj7":"C# E G# C ",
"Dm/maj7":"D F A C# ",
"D#m/maj7":"D# F# A# D ",
"Em/maj7":"E G B D# ",
"Fm/maj7":"F G# C E ",
"F#m/maj7":"F# A C# F ",
"Gm/maj7":"G A# D F# ",
"G#m/maj7":"G# B D# G ",
"Am/maj7":"A C E G# ",
"A#m/maj7":"A# C# F A ",
"Bm/maj7":"B D F# A# ",
"Cmaj7+5":"C E G# B ",
"C#maj7+5":"C# F A C ",
"Dmaj7+5":"D F# A# C# ",
"D#maj7+5":"D# G B D ",
"Emaj7+5":"E G# C D# ",
"Fmaj7+5":"F A C# E ",
"F#maj7+5":"F# A# D F ",
"Gmaj7+5":"G B D# F# ",
"G#maj7+5":"G# C E G ",
"Amaj7+5":"A C# F G# ",
"A#maj7+5":"A# D F# A ",
"Bmaj7+5":"B D# G A# ",
"Cmaj7-5":"C E F# B ",
"C#maj7-5":"C# F G C ",
"Dmaj7-5":"D F# G# C# ",
"D#maj7-5":"D# G A D ",
"Emaj7-5":"E G# A# D# ",
"Fmaj7-5":"F A B E ",
"F#maj7-5":"F# A# C F ",
"Gmaj7-5":"G B C# F# ",
"G#maj7-5":"G# C D G ",
"Amaj7-5":"A C# D# G# ",
"A#maj7-5":"A# D E A ",
"Bmaj7-5":"B D# F A# ",
"C9":"C E G A# D ",
"C#9":"C# F G# B D# ",
"D9":"D F# A C E ",
"D#9":"D# G A# C# F ",
"E9":"E G# B D F# ",
"F9":"F A C D# G ",
"F#9":"F# A# C# E G# ",
"G9":"G B D F A ",
"G#9":"G# C D# F# A# ",
"A9":"A C# E G B ",
"A#9":"A# D F G# C ",
"B9":"B D# F# A C# ",
"Cm9":"C D# G A# D ",
"C#m9":"C# E G# B D# ",
"Dm9":"D F A C E ",
"D#m9":"D# F# A# C# F ",
"Em9":"E G B D F# ",
"Fm9":"F G# C D# G ",
"F#m9":"F# A C# E G# ",
"Gm9":"G A# D F A ",
"G#m9":"G# B D# F# A# ",
"Am9":"A C E G B ",
"A#m9":"A# C# F G# C ",
"Bm9":"B D F# A C# ",
"Cmaj9":"C E G B D ",
"C#maj9":"C# F G# C D# ",
"Dmaj9":"D F# A C# E ",
"D#maj9":"D# G A# D F ",
"Emaj9":"E G# B D# F# ",
"Fmaj9":"F A C E G ",
"F#maj9":"F# A# C# F G# ",
"Gmaj9":"G B D F# A ",
"G#maj9":"G# C D# G A# ",
"Amaj9":"A C# E G# B ",
"A#maj9":"A# D F A C ",
"Bmaj9":"B D# F# A# C# ",
"C7+9":"C E G A# D# ",
"C#7+9":"C# F G# B E ",
"D7+9":"D F# A C F ",
"D#7+9":"D# G A# C# F# ",
"E7+9":"E G# B D G ",
"F7+9":"F A C D# G# ",
"F#7+9":"F# A# C# E A ",
"G7+9":"G B D F A# ",
"G#7+9":"G# C D# F# B ",
"A7+9":"A C# E G C ",
"A#7+9":"A# D F G# C# ",
"B7+9":"B D# F# A D ",
"C7-9":"C E G A# C# ",
"C#7-9":"C# F G# B D ",
"D7-9":"D F# A C D# ",
"D#7-9":"D# G A# C# E ",
"E7-9":"E G# B D F ",
"F7-9":"F A C D# F# ",
"F#7-9":"F# A# C# E G ",
"G7-9":"G B D F G# ",
"G#7-9":"G# C D# F# A ",
"A7-9":"A C# E G A# ",
"A#7-9":"A# D F G# B ",
"B7-9":"B D# F# A C ",
"C7+9-5":"C E F# A# D# ",
"C#7+9-5":"C# F G B E ",
"D7+9-5":"D F# G# C F ",
"D#7+9-5":"D# G A C# F# ",
"E7+9-5":"E G# A# D G ",
"F7+9-5":"F A B D# G# ",
"F#7+9-5":"F# A# C E A ",
"G7+9-5":"G B C# F A# ",
"G#7+9-5":"G# C D F# B ",
"A7+9-5":"A C# D# G C ",
"A#7+9-5":"A# D E G# C# ",
"B7+9-5":"B D# F A D ",
"C6/9":"C E G A D ",
"C#6/9":"C# F G# A# D# ",
"D6/9":"D F# A B E ",
"D#6/9":"D# G A# C F ",
"E6/9":"E G# B C# F# ",
"F6/9":"F A C D G ",
"F#6/9":"F# A# C# D# G# ",
"G6/9":"G B D E A ",
"G#6/9":"G# C D# F A# ",
"A6/9":"A C# E F# B ",
"A#6/9":"A# D F G C ",
"B6/9":"B D# F# G# C# ",
"C9+5":"C E G# A# D ",
"C#9+5":"C# F A B D# ",
"D9+5":"D F# A# C E ",
"D#9+5":"D# G B C# F ",
"E9+5":"E G# C D F# ",
"F9+5":"F A C# D# G ",
"F#9+5":"F# A# D E G# ",
"G9+5":"G B D# F A ",
"G#9+5":"G# C E F# A# ",
"A9+5":"A C# F G B ",
"A#9+5":"A# D F# G# C ",
"B9+5":"B D# G A C# ",
"C9-5":"C E F# A# D ",
"C#9-5":"C# F G B D# ",
"D9-5":"D F# G# C E ",
"D#9-5":"D# G A C# F ",
"E9-5":"E G# A# D F# ",
"F9-5":"F A B D# G ",
"F#9-5":"F# A# C E G# ",
"G9-5":"G B C# F A ",
"G#9-5":"G# C D F# A# ",
"A9-5":"A C# D# G B ",
"A#9-5":"A# D E G# C ",
"B9-5":"B D# F A C# ",
"Cm9-5":"C D# F# A# D ",
"C#m9-5":"C# E G B D# ",
"Dm9-5":"D F G# C E ",
"D#m9-5":"D# F# A C# F ",
"Em9-5":"E G A# D F# ",
"Fm9-5":"F G# B D# G ",
"F#m9-5":"F# A C E G# ",
"Gm9-5":"G A# C# F A ",
"G#m9-5":"G# B D F# A# ",
"Am9-5":"A C D# G B ",
"A#m9-5":"A# C# E G# C ",
"Bm9-5":"B D F A C# ",
"C11":"C E G A# D F ",
"C#11":"C# F G# B D# F# ",
"D11":"D F# A C E G ",
"D#11":"D# G A# C# F G# ",
"E11":"E G# B D F# A ",
"F11":"F A C D# G A# ",
"F#11":"F# A# C# E G# B ",
"G11":"G B D F A C ",
"G#11":"G# C D# F# A# C# ",
"A11":"A C# E G B D ",
"A#11":"A# D F G# C D# ",
"B11":"B D# F# A C# E ",
"Cm11":"C D# G A# D F ",
"C#m11":"C# E G# B D# F# ",
"Dm11":"D F A C E G ",
"D#m11":"D# F# A# C# F G# ",
"Em11":"E G B D F# A ",
"Fm11":"F G# C D# G A# ",
"F#m11":"F# A C# E G# B ",
"Gm11":"G A# D F A C ",
"G#m11":"G# B D# F# A# C# ",
"Am11":"A C E G B D ",
"A#m11":"A# C# F G# C D# ",
"Bm11":"B D F# A C# E ",
"C11-9":"C E G A# C# F ",
"C#11-9":"C# F G# B D F# ",
"D11-9":"D F# A C D# G ",
"D#11-9":"D# G A# C# E G# ",
"E11-9":"E G# B D F A ",
"F11-9":"F A C D# F# A# ",
"F#11-9":"F# A# C# E G B ",
"G11-9":"G B D F G# C ",
"G#11-9":"G# C D# F# A C# ",
"A11-9":"A C# E G A# D ",
"A#11-9":"A# D F G# B D# ",
"B11-9":"B D# F# A C E ",
"C13":"C E G A# D F A ",
"C#13":"C# F G# B D# F# A# ",
"D13":"D F# A C E G B ",
"D#13":"D# G A# C# F G# C ",
"E13":"E G# B D F# A C# ",
"F13":"F A C D# G A# D ",
"F#13":"F# A# C# E G# B D# ",
"G13":"G B D F A C E ",
"G#13":"G# C D# F# A# C# F ",
"A13":"A C# E G B D F# ",
"A#13":"A# D F G# C D# G ",
"B13":"B D# F# A C# E G# ",
"Cm13":"C D# G A# D F A ",
"C#m13":"C# E G# B D# F# A# ",
"Dm13":"D F A C E G B ",
"D#m13":"D# F# A# C# F G# C ",
"Em13":"E G B D F# A C# ",
"Fm13":"F G# C D# G A# D ",
"F#m13":"F# A C# E G# B D# ",
"Gm13":"G A# D F A C E ",
"G#m13":"G# B D# F# A# C# F ",
"Am13":"A C E G B D F# ",
"A#m13":"A# C# F G# C D# G ",
"Bm13":"B D F# A C# E G# ",
"Cmaj13":"C E G B D F A ",
"C#maj13":"C# F G# C D# F# A# ",
"Dmaj13":"D F# A C# E G B ",
"D#maj13":"D# G A# D F G# C ",
"Emaj13":"E G# B D# F# A C# ",
"Fmaj13":"F A C E G A# D ",
"F#maj13":"F# A# C# F G# B D# ",
"Gmaj13":"G B D F# A C E ",
"G#maj13":"G# C D# G A# C# F ",
"Amaj13":"A C# E G# B D F# ",
"A#maj13":"A# D F A C D# G ",
"Bmaj13":"B D# F# A# C# E G# ",
"Cadd9":"C E G D ",
"C#add9":"C# F G# D# ",
"Dadd9":"D F# A E ",
"D#add9":"D# G A# F ",
"Eadd9":"E G# B F# ",
"Fadd9":"F A C G ",
"F#add9":"F# A# C# G# ",
"Gadd9":"G B D A ",
"G#add9":"G# C D# A# ",
"Aadd9":"A C# E B ",
"A#add9":"A# D F C ",
"Badd9":"B D# F# C# ",
"Cmadd9":"C D# G D ",
"C#madd9":"C# E G# D# ",
"Dmadd9":"D F A E ",
"D#madd9":"D# F# A# F ",
"Emadd9":"E G B F# ",
"Fmadd9":"F G# C G ",
"F#madd9":"F# A C# G# ",
"Gmadd9":"G A# D A ",
"G#madd9":"G# B D# A# ",
"Amadd9":"A C E B ",
"A#madd9":"A# C# F C ",
"Bmadd9":"B D F# C# ",
"Csus2":"C D G ",
"C#sus2":"C# D# G# ",
"Dsus2":"D E A ",
"D#sus2":"D# F A# ",
"Esus2":"E F# B ",
"Fsus2":"F G C ",
"F#sus2":"F# G# C# ",
"Gsus2":"G A D ",
"G#sus2":"G# A# D# ",
"Asus2":"A B E ",
"A#sus2":"A# C F ",
"Bsus2":"B C# F# ",
"C5":"C G ",
"C#5":"C# G# ",
"D5":"D A ",
"D#5":"D# A# ",
"E5":"E B ",
"F5":"F C ",
"F#5":"F# C# ",
"G5":"G D ",
"G#5":"G# D# ",
"A5":"A E ",
"A#5":"A# F ",
"B5":"B F# "};


Utils.scales = {
"C Major":"C D E F G A B ",
"C# Major":"C# D# F F# G# A# C ",
"D Major":"D E F# G A B C# ",
"D# Major":"D# F G G# A# C D ",
"E Major":"E F# G# A B C# D# ",
"F Major":"F G A A# C D E ",
"F# Major":"F# G# A# B C# D# F ",
"G Major":"G A B C D E F# ",
"G# Major":"G# A# C C# D# F G ",
"A Major":"A B C# D E F# G# ",
"A# Major":"A# C D D# F G A ",
"B Major":"B C# D# E F# G# A# ",
"C natural minor":"C D D# F G G# A# ",
"C# natural minor":"C# D# E F# G# A B ",
"D natural minor":"D E F G A A# C ",
"D# natural minor":"D# F F# G# A# B C# ",
"E natural minor":"E F# G A B C D ",
"F natural minor":"F G G# A# C C# D# ",
"F# natural minor":"F# G# A B C# D E ",
"G natural minor":"G A A# C D D# F ",
"G# natural minor":"G# A# B C# D# E F# ",
"A natural minor":"A B C D E F G ",
"A# natural minor":"A# C C# D# F F# G# ",
"B natural minor":"B C# D E F# G A ",
"C harmonic minor":"C D D# F G G# B ",
"C# harmonic minor":"C# D# E F# G# A C ",
"D harmonic minor":"D E F G A A# C# ",
"D# harmonic minor":"D# F F# G# A# B D ",
"E harmonic minor":"E F# G A B C D# ",
"F harmonic minor":"F G G# A# C C# E ",
"F# harmonic minor":"F# G# A B C# D F ",
"G harmonic minor":"G A A# C D D# F# ",
"G# harmonic minor":"G# A# B C# D# E G ",
"A harmonic minor":"A B C D E F G# ",
"A# harmonic minor":"A# C C# D# F F# A ",
"B harmonic minor":"B C# D E F# G A# ",
"C melodic minor":"C D D# F G A B ",
"C# melodic minor":"C# D# E F# G# A# C ",
"D melodic minor":"D E F G A B C# ",
"D# melodic minor":"D# F F# G# A# C D ",
"E melodic minor":"E F# G A B C# D# ",
"F melodic minor":"F G G# A# C D E ",
"F# melodic minor":"F# G# A B C# D# F ",
"G melodic minor":"G A A# C D E F# ",
"G# melodic minor":"G# A# B C# D# F G ",
"A melodic minor":"A B C D E F# G# ",
"A# melodic minor":"A# C C# D# F G A ",
"B melodic minor":"B C# D E F# G# A# ",
"C major pentatonic":"C D E G A ",
"C# major pentatonic":"C# D# F G# A# ",
"D major pentatonic":"D E F# A B ",
"D# major pentatonic":"D# F G A# C ",
"E major pentatonic":"E F# G# B C# ",
"F major pentatonic":"F G A C D ",
"F# major pentatonic":"F# G# A# C# D# ",
"G major pentatonic":"G A B D E ",
"G# major pentatonic":"G# A# C D# F ",
"A major pentatonic":"A B C# E F# ",
"A# major pentatonic":"A# C D F G ",
"B major pentatonic":"B C# D# F# G# ",
"C minor pentatonic":"C D# F G A# ",
"C# minor pentatonic":"C# E F# G# B ",
"D minor pentatonic":"D F G A C ",
"D# minor pentatonic":"D# F# G# A# C# ",
"E minor pentatonic":"E G A B D ",
"F minor pentatonic":"F G# A# C D# ",
"F# minor pentatonic":"F# A B C# E ",
"G minor pentatonic":"G A# C D F ",
"G# minor pentatonic":"G# B C# D# F# ",
"A minor pentatonic":"A C D E G ",
"A# minor pentatonic":"A# C# D# F G# ",
"B minor pentatonic":"B D E F# A ",
"C blues":"C D# F F# G A# ",
"C# blues":"C# E F# G G# B ",
"D blues":"D F G G# A C ",
"D# blues":"D# F# G# A A# C# ",
"E blues":"E G A A# B D ",
"F blues":"F G# A# B C D# ",
"F# blues":"F# A B C C# E ",
"G blues":"G A# C C# D F ",
"G# blues":"G# B C# D D# F# ",
"A blues":"A C D D# E G ",
"A# blues":"A# C# D# E F G# ",
"B blues":"B D E F F# A ",
"C minor blues":"C D D# F F# G G# A# ",
"C# minor blues":"C# D# E F# G G# A B ",
"D minor blues":"D E F G G# A A# C ",
"D# minor blues":"D# F F# G# A A# B C# ",
"E minor blues":"E F# G A A# B C D ",
"F minor blues":"F G G# A# B C C# D# ",
"F# minor blues":"F# G# A B C C# D E ",
"G minor blues":"G A A# C C# D D# F ",
"G# minor blues":"G# A# B C# D D# E F# ",
"A minor blues":"A B C D D# E F G ",
"A# minor blues":"A# C C# D# E F F# G# ",
"B minor blues":"B C# D E F F# G A ",
"C major blues":"C D D# E F F# G A A# ",
"C# major blues":"C# D# E F F# G G# A# B ",
"D major blues":"D E F F# G G# A B C ",
"D# major blues":"D# F F# G G# A A# C C# ",
"E major blues":"E F# G G# A A# B C# D ",
"F major blues":"F G G# A A# B C D D# ",
"F# major blues":"F# G# A A# B C C# D# E ",
"G major blues":"G A A# B C C# D E F ",
"G# major blues":"G# A# B C C# D D# F F# ",
"A major blues":"A B C C# D D# E F# G ",
"A# major blues":"A# C C# D D# E F G G# ",
"B major blues":"B C# D D# E F F# G# A ",
"C augmented":"C D E F# G# A# ",
"C# augmented":"C# D# F G A B ",
"D augmented":"D E F# G# A# C ",
"D# augmented":"D# F G A B C# ",
"E augmented":"E F# G# A# C D ",
"F augmented":"F G A B C# D# ",
"F# augmented":"F# G# A# C D E ",
"G augmented":"G A B C# D# F ",
"G# augmented":"G# A# C D E F# ",
"A augmented":"A B C# D# F G ",
"A# augmented":"A# C D E F# G# ",
"B augmented":"B C# D# F G A ",
"C diminished":"C D D# F F# G# A B ",
"C# diminished":"C# D# E F# G A A# C ",
"D diminished":"D E F G G# A# B C# ",
"D# diminished":"D# F F# G# A B C D ",
"E diminished":"E F# G A A# C C# D# ",
"F diminished":"F G G# A# B C# D E ",
"F# diminished":"F# G# A B C D D# F ",
"G diminished":"G A A# C C# D# E F# ",
"G# diminished":"G# A# B C# D E F G ",
"A diminished":"A B C D D# F F# G# ",
"A# diminished":"A# C C# D# E F# G A ",
"B diminished":"B C# D E F G G# A# ",
"C Phrygian-Dominant":"C C# E F G G# A# ",
"C# Phrygian-Dominant":"C# D F F# G# A B ",
"D Phrygian-Dominant":"D D# F# G A A# C ",
"D# Phrygian-Dominant":"D# E G G# A# B C# ",
"E Phrygian-Dominant":"E F G# A B C D ",
"F Phrygian-Dominant":"F F# A A# C C# D# ",
"F# Phrygian-Dominant":"F# G A# B C# D E ",
"G Phrygian-Dominant":"G G# B C D D# F ",
"G# Phrygian-Dominant":"G# A C C# D# E F# ",
"A Phrygian-Dominant":"A A# C# D E F G ",
"A# Phrygian-Dominant":"A# B D D# F F# G# ",
"B Phrygian-Dominant":"B C D# E F# G A ",
"C Dorian":"C D D# F G A A# ",
"C# Dorian":"C# D# E F# G# A# B ",
"D Dorian":"D E F G A B C ",
"D# Dorian":"D# F F# G# A# C C# ",
"E Dorian":"E F# G A B C# D ",
"F Dorian":"F G G# A# C D D# ",
"F# Dorian":"F# G# A B C# D# E ",
"G Dorian":"G A A# C D E F ",
"G# Dorian":"G# A# B C# D# F F# ",
"A Dorian":"A B C D E F# G ",
"A# Dorian":"A# C C# D# F G G# ",
"B Dorian":"B C# D E F# G# A ",
"C Phrygian":"C C# D# F G G# A# ",
"C# Phrygian":"C# D E F# G# A B ",
"D Phrygian":"D D# F G A A# C ",
"D# Phrygian":"D# E F# G# A# B C# ",
"E Phrygian":"E F G A B C D ",
"F Phrygian":"F F# G# A# C C# D# ",
"F# Phrygian":"F# G A B C# D E ",
"G Phrygian":"G G# A# C D D# F ",
"G# Phrygian":"G# A B C# D# E F# ",
"A Phrygian":"A A# C D E F G ",
"A# Phrygian":"A# B C# D# F F# G# ",
"B Phrygian":"B C D E F# G A ",
"C Lydian":"C D E F# G A B ",
"C# Lydian":"C# D# F G G# A# C ",
"D Lydian":"D E F# G# A B C# ",
"D# Lydian":"D# F G A A# C D ",
"E Lydian":"E F# G# A# B C# D# ",
"F Lydian":"F G A B C D E ",
"F# Lydian":"F# G# A# C C# D# F ",
"G Lydian":"G A B C# D E F# ",
"G# Lydian":"G# A# C D D# F G ",
"A Lydian":"A B C# D# E F# G# ",
"A# Lydian":"A# C D E F G A ",
"B Lydian":"B C# D# F F# G# A# ",
"C Mixolydian":"C D E F G A A# ",
"C# Mixolydian":"C# D# F F# G# A# B ",
"D Mixolydian":"D E F# G A B C ",
"D# Mixolydian":"D# F G G# A# C C# ",
"E Mixolydian":"E F# G# A B C# D ",
"F Mixolydian":"F G A A# C D D# ",
"F# Mixolydian":"F# G# A# B C# D# E ",
"G Mixolydian":"G A B C D E F ",
"G# Mixolydian":"G# A# C C# D# F F# ",
"A Mixolydian":"A B C# D E F# G ",
"A# Mixolydian":"A# C D D# F G G# ",
"B Mixolydian":"B C# D# E F# G# A ",
"C Locrian":"C C# D# F F# G# A# ",
"C# Locrian":"C# D E F# G A B ",
"D Locrian":"D D# F G G# A# C ",
"D# Locrian":"D# E F# G# A B C# ",
"E Locrian":"E F G A A# C D ",
"F Locrian":"F F# G# A# B C# D# ",
"F# Locrian":"F# G A B C D E ",
"G Locrian":"G G# A# C C# D# F ",
"G# Locrian":"G# A B C# D E F# ",
"A Locrian":"A A# C D D# F G ",
"A# Locrian":"A# B C# D# E F# G# ",
"B Locrian":"B C D E F G A ",
"C jazz melodic minor":"C D D# F G A B ",
"C# jazz melodic minor":"C# D# E F# G# A# C ",
"D jazz melodic minor":"D E F G A B C# ",
"D# jazz melodic minor":"D# F F# G# A# C D ",
"E jazz melodic minor":"E F# G A B C# D# ",
"F jazz melodic minor":"F G G# A# C D E ",
"F# jazz melodic minor":"F# G# A B C# D# F ",
"G jazz melodic minor":"G A A# C D E F# ",
"G# jazz melodic minor":"G# A# B C# D# F G ",
"A jazz melodic minor":"A B C D E F# G# ",
"A# jazz melodic minor":"A# C C# D# F G A ",
"B jazz melodic minor":"B C# D E F# G# A# ",
"C Dorian b2":"C C# D# F G A A# ",
"C# Dorian b2":"C# D E F# G# A# B ",
"D Dorian b2":"D D# F G A B C ",
"D# Dorian b2":"D# E F# G# A# C C# ",
"E Dorian b2":"E F G A B C# D ",
"F Dorian b2":"F F# G# A# C D D# ",
"F# Dorian b2":"F# G A B C# D# E ",
"G Dorian b2":"G G# A# C D E F ",
"G# Dorian b2":"G# A B C# D# F F# ",
"A Dorian b2":"A A# C D E F# G ",
"A# Dorian b2":"A# B C# D# F G G# ",
"B Dorian b2":"B C D E F# G# A ",
"C Lydian augmented":"C D E F# G# A B ",
"C# Lydian augmented":"C# D# F G A A# C ",
"D Lydian augmented":"D E F# G# A# B C# ",
"D# Lydian augmented":"D# F G A B C D ",
"E Lydian augmented":"E F# G# A# C C# D# ",
"F Lydian augmented":"F G A B C# D E ",
"F# Lydian augmented":"F# G# A# C D D# F ",
"G Lydian augmented":"G A B C# D# E F# ",
"G# Lydian augmented":"G# A# C D E F G ",
"A Lydian augmented":"A B C# D# F F# G# ",
"A# Lydian augmented":"A# C D E F# G A ",
"B Lydian augmented":"B C# D# F G G# A# ",
"C Lydian b7":"C D E F# G A A# ",
"C# Lydian b7":"C# D# F G G# A# B ",
"D Lydian b7":"D E F# G# A B C ",
"D# Lydian b7":"D# F G A A# C C# ",
"E Lydian b7":"E F# G# A# B C# D ",
"F Lydian b7":"F G A B C D D# ",
"F# Lydian b7":"F# G# A# C C# D# E ",
"G Lydian b7":"G A B C# D E F ",
"G# Lydian b7":"G# A# C D D# F F# ",
"A Lydian b7":"A B C# D# E F# G ",
"A# Lydian b7":"A# C D E F G G# ",
"B Lydian b7":"B C# D# F F# G# A ",
"C Mixolydian b13":"C D E F G G# A# ",
"C# Mixolydian b13":"C# D# F F# G# A B ",
"D Mixolydian b13":"D E F# G A A# C ",
"D# Mixolydian b13":"D# F G G# A# B C# ",
"E Mixolydian b13":"E F# G# A B C D ",
"F Mixolydian b13":"F G A A# C C# D# ",
"F# Mixolydian b13":"F# G# A# B C# D E ",
"G Mixolydian b13":"G A B C D D# F ",
"G# Mixolydian b13":"G# A# C C# D# E F# ",
"A Mixolydian b13":"A B C# D E F G ",
"A# Mixolydian b13":"A# C D D# F F# G# ",
"B Mixolydian b13":"B C# D# E F# G A ",
"C Locrian #2":"C D D# F F# G# A# ",
"C# Locrian #2":"C# D# E F# G A B ",
"D Locrian #2":"D E F G G# A# C ",
"D# Locrian #2":"D# F F# G# A B C# ",
"E Locrian #2":"E F# G A A# C D ",
"F Locrian #2":"F G G# A# B C# D# ",
"F# Locrian #2":"F# G# A B C D E ",
"G Locrian #2":"G A A# C C# D# F ",
"G# Locrian #2":"G# A# B C# D E F# ",
"A Locrian #2":"A B C D D# F G ",
"A# Locrian #2":"A# C C# D# E F# G# ",
"B Locrian #2":"B C# D E F G A ",
"C super Locrian":"C C# D# E F# G# A# ",
"C# super Locrian":"C# D E F G A B ",
"D super Locrian":"D D# F F# G# A# C ",
"D# super Locrian":"D# E F# G A B C# ",
"E super Locrian":"E F G G# A# C D ",
"F super Locrian":"F F# G# A B C# D# ",
"F# super Locrian":"F# G A A# C D E ",
"G super Locrian":"G G# A# B C# D# F ",
"G# super Locrian":"G# A B C D E F# ",
"A super Locrian":"A A# C C# D# F G ",
"A# super Locrian":"A# B C# D E F# G# ",
"B super Locrian":"B C D D# F G A ",
"C whole half diminished":"C D D# F F# G# A B ",
"C# whole half diminished":"C# D# E F# G A A# C ",
"D whole half diminished":"D E F G G# A# B C# ",
"D# whole half diminished":"D# F F# G# A B C D ",
"E whole half diminished":"E F# G A A# C C# D# ",
"F whole half diminished":"F G G# A# B C# D E ",
"F# whole half diminished":"F# G# A B C D D# F ",
"G whole half diminished":"G A A# C C# D# E F# ",
"G# whole half diminished":"G# A# B C# D E F G ",
"A whole half diminished":"A B C D D# F F# G# ",
"A# whole half diminished":"A# C C# D# E F# G A ",
"B whole half diminished":"B C# D E F G G# A# ",
"C half whole diminished":"C C# D# E F# G A A# ",
"C# half whole diminished":"C# D E F G G# A# B ",
"D half whole diminished":"D D# F F# G# A B C ",
"D# half whole diminished":"D# E F# G A A# C C# ",
"E half whole diminished":"E F G G# A# B C# D ",
"F half whole diminished":"F F# G# A B C D D# ",
"F# half whole diminished":"F# G A A# C C# D# E ",
"G half whole diminished":"G G# A# B C# D E F ",
"G# half whole diminished":"G# A B C D D# F F# ",
"A half whole diminished":"A A# C C# D# E F# G ",
"A# half whole diminished":"A# B C# D E F G G# ",
"B half whole diminished":"B C D D# F F# G# A ",
"C enigmatic":"C C# E F# G# A# B ",
"C# enigmatic":"C# D F G A B C ",
"D enigmatic":"D D# F# G# A# C C# ",
"D# enigmatic":"D# E G A B C# D ",
"E enigmatic":"E F G# A# C D D# ",
"F enigmatic":"F F# A B C# D# E ",
"F# enigmatic":"F# G A# C D E F ",
"G enigmatic":"G G# B C# D# F F# ",
"G# enigmatic":"G# A C D E F# G ",
"A enigmatic":"A A# C# D# F G G# ",
"A# enigmatic":"A# B D E F# G# A ",
"B enigmatic":"B C D# F G A A# ",
"C double harmonic":"C C# E F G G# B ",
"C# double harmonic":"C# D F F# G# A C ",
"D double harmonic":"D D# F# G A A# C# ",
"D# double harmonic":"D# E G G# A# B D ",
"E double harmonic":"E F G# A B C D# ",
"F double harmonic":"F F# A A# C C# E ",
"F# double harmonic":"F# G A# B C# D F ",
"G double harmonic":"G G# B C D D# F# ",
"G# double harmonic":"G# A C C# D# E G ",
"A double harmonic":"A A# C# D E F G# ",
"A# double harmonic":"A# B D D# F F# A ",
"B double harmonic":"B C D# E F# G A# ",
"C Hungarian minor":"C D D# F# G G# B ",
"C# Hungarian minor":"C# D# E G G# A C ",
"D Hungarian minor":"D E F G# A A# C# ",
"D# Hungarian minor":"D# F F# A A# B D ",
"E Hungarian minor":"E F# G A# B C D# ",
"F Hungarian minor":"F G G# B C C# E ",
"F# Hungarian minor":"F# G# A C C# D F ",
"G Hungarian minor":"G A A# C# D D# F# ",
"G# Hungarian minor":"G# A# B D D# E G ",
"A Hungarian minor":"A B C D# E F G# ",
"A# Hungarian minor":"A# C C# E F F# A ",
"B Hungarian minor":"B C# D F F# G A# ",
"C Persian":"C C# E F F# G# B ",
"C# Persian":"C# D F F# G A C ",
"D Persian":"D D# F# G G# A# C# ",
"D# Persian":"D# E G G# A B D ",
"E Persian":"E F G# A A# C D# ",
"F Persian":"F F# A A# B C# E ",
"F# Persian":"F# G A# B C D F ",
"G Persian":"G G# B C C# D# F# ",
"G# Persian":"G# A C C# D E G ",
"A Persian":"A A# C# D D# F G# ",
"A# Persian":"A# B D D# E F# A ",
"B Persian":"B C D# E F G A# ",
"C Arabian":"C D E F F# G# A# ",
"C# Arabian":"C# D# F F# G A B ",
"D Arabian":"D E F# G G# A# C ",
"D# Arabian":"D# F G G# A B C# ",
"E Arabian":"E F# G# A A# C D ",
"F Arabian":"F G A A# B C# D# ",
"F# Arabian":"F# G# A# B C D E ",
"G Arabian":"G A B C C# D# F ",
"G# Arabian":"G# A# C C# D E F# ",
"A Arabian":"A B C# D D# F G ",
"A# Arabian":"A# C D D# E F# G# ",
"B Arabian":"B C# D# E F G A ",
"C Japanese":"C C# F G G# ",
"C# Japanese":"C# D F# G# A ",
"D Japanese":"D D# G A A# ",
"D# Japanese":"D# E G# A# B ",
"E Japanese":"E F A B C ",
"F Japanese":"F F# A# C C# ",
"F# Japanese":"F# G B C# D ",
"G Japanese":"G G# C D D# ",
"G# Japanese":"G# A C# D# E ",
"A Japanese":"A A# D E F ",
"A# Japanese":"A# B D# F F# ",
"B Japanese":"B C E F# G ",
"C Egyptian":"C D F G A# ",
"C# Egyptian":"C# D# F# G# B ",
"D Egyptian":"D E G A C ",
"D# Egyptian":"D# F G# A# C# ",
"E Egyptian":"E F# A B D ",
"F Egyptian":"F G A# C D# ",
"F# Egyptian":"F# G# B C# E ",
"G Egyptian":"G A C D F ",
"G# Egyptian":"G# A# C# D# F# ",
"A Egyptian":"A B D E G ",
"A# Egyptian":"A# C D# F G# ",
"B Egyptian":"B C# E F# A ",
"C Hirajoshi":"C D D# G G# ",
"C# Hirajoshi":"C# D# E G# A ",
"D Hirajoshi":"D E F A A# ",
"D# Hirajoshi":"D# F F# A# B ",
"E Hirajoshi":"E F# G B C ",
"F Hirajoshi":"F G G# C C# ",
"F# Hirajoshi":"F# G# A C# D ",
"G Hirajoshi":"G A A# D D# ",
"G# Hirajoshi":"G# A# B D# E ",
"A Hirajoshi":"A B C E F ",
"A# Hirajoshi":"A# C C# F F# ",
"B Hirajoshi":"B C# D F# G "} ;


Utils.chordsArray = [];
for(var k in Utils.chords){
	Utils.chordsArray.push(Utils.chords[k]);
}

Utils.scalesArray = [];
for(var k in Utils.scales){
	Utils.scalesArray.push(Utils.scales[k]);
}


module.exports = Utils;
